### ISSUE TITLE
Where is data_fifo_32 and data_fifo_64?

### ISSUE THREAD

**Issue by Arnab-hardware** [Architech-Silica/Designing-a-Custom-AXI-Master-using-BFMs#3]
I can see that the components of data_fifo_32 and data_fifo_64 are used in AXI_master_transaction but I could not find the files. Please tell me where I can get those two files.

Thanks.

**Comment by jrrk** [comment]
If you are using Vivado, these components can be created from the IP 
customisation panel. e.g.

COMPONENT data_fifo_32
   PORT (
     clk : IN STD_LOGIC;
     rst : IN STD_LOGIC;
     din : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
     wr_en : IN STD_LOGIC;
     rd_en : IN STD_LOGIC;
     dout : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
     full : OUT STD_LOGIC;
     empty : OUT STD_LOGIC
   );
END COMPONENT;

IP configurations may be captured in a .xci file, of which an example is 
attached (may need modifying).

**Comment by Arnab-hardware** [comment]
Thanks for your reply. I am not familiar at creation of "components" from Vivado. I know how to create IPs but for that I need to provide the definition of the entity. Anyway, I would suggest you to modify the readme text to clearly indicate the steps required to use the AXI master. Otherwise, I think that the files available as it is, will not be useful.

**Comment by jrrk** [comment]
Did you get the attached.xci files? I assume the mailing list will scrub them. The Vivado help covers the process of importing and customising IP. It is impossible to be more specific because you never mentioned what FPGA technology you are targeting. Trust me this is a straightforward task once you know, and you will learn so much more by doing some customisation yourself. I am not affiliated with the authors in any way. Whether the block is useful to you is outside the scope of this discussion, but I would suggest you show more enthusiasm rather than less if somebody offers you something for free and you need help with it.

**Comment by Arnab-hardware** [comment]
I did not get any file as you guessed correctly. I never wanted to show any other feeling than thankfulness for your reply. If you consider my suggestion of modifying the readme file, consider that line for the authors because you are not associated with them. Regarding your suggestion of learning, I agree that I have no other option left than doing that. The point of using a set of files from Github really is not satisfied in that case. I was not asking any Vivado question here and I am not going to do so because this section is specific to this project only which I was trying to use. Please try to understand that any body trying to use these files will be unsuccessful if they do it blindly. The entity definitions are absent and it is also not mentioned anywhere that we need to create or modify the IP.

Thanks again.

**Comment by jrrk** [comment]
Just copy your request to me personally from your personal email, and I will forward again with attachments. As an unconnected third party I obviously can’t go modifying the readme.

**Comment by mp1609** [comment]
Hi there,

I had the same issue and was wondering how to get this code working....
So, if anybody wants to know how to get this working:

You have to do this twice, one for 32bit fifo and the other one for 64bit.

For 64bit do the following:

Go to your repo and rightclick the "fifo_generator" and select "customize ip":
![1_customize_ip](https://user-images.githubusercontent.com/38104477/48340637-611d4f00-e66b-11e8-85ea-e21922a51e32.png)

Set the IP name to "data_fifo_64"
![2_set_name](https://user-images.githubusercontent.com/38104477/48340642-64b0d600-e66b-11e8-9e8b-1a9d02547c65.png)

Set datawidth to 64 bit
![3_set_data_width](https://user-images.githubusercontent.com/38104477/48340646-667a9980-e66b-11e8-9998-e79e3adbad9e.png)

BE CAREFUL! On my Vivado 2017.4 there seems to be a bug in the last step: I had to select the ASYNC RESET again, otherwise the port of RST was "ARST" instead of "RST" as defined in this example code...

Done.
